### ISSUE TITLE
Would it be possible to gain access to the organization to continue this page?

### ISSUE THREAD

**Issue by kfischer-okarin** [awesome-dragonruby/awesome-dragonruby#9]
Hello @Lax,

Would it be possible to be added to the https://github.com/awesome-dragonruby organization so we could continue this page in the community?

**Comment by Lax** [comment]
Hi, I invited you to the organization, you may check that.

**Comment by kfischer-okarin** [comment]
Thanks for your reply! We continued to work on this page on and off in our own organization - so I think we will merge it into that organization !!
